config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  get 'aws/openam', action: :aws_openam, controller: 'home'
  get 'aws/onelogin', action: :aws_onelogin, controller: 'home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def aws_openam
    render html: Idp::Openam.new(current_user).aws_redirect_html.body.html_safe
  end
  def aws_onelogin
    @saml_assertion = Idp::Onelogin.new(current_user).aws_saml_assertion
    render layout: nil
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def create
    super

    if resource.errors.count.zero?
      Idp::Openam.new(resource).create_user
      Idp::Onelogin.new(resource).create_user.assign_role.change_password
    end
  end

  def update
    super

    if resource.errors.count.zero?
      Idp::Openam.new(resource).change_password
      Idp::Onelogin.new(resource).change_password
    end
  end

  def destroy
    super

    if resource.errors.count.zero?
      Idp::Openam.new(resource).delete_user
      Idp::Onelogin.new(resource).delete_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/aws_onelogin.html.slim
html
  head
    title
      | Access rights validated
  body[onload="document.forms[0].submit()"]
    form[method="post" action="https://signin.aws.amazon.com/saml"]
      input[type="hidden" name="SAMLResponse" value="#{@saml_assertion}"]
      noscript
        input[type="submit" value="Submit SAMLResponse data"]

app/views/home/index.html.slim
h1
  | SAML認証

= link_to "#{ENV['OPENAM_URI']}", { class: 'btn btn-primary', target: '_blank' } do
  | OpenAM

.
  | OpenAM Username: #{current_user.email unless current_user.nil?}
.
  | OpenAM Password: #{current_user.encrypted_password unless current_user.nil?}

.
  = link_to aws_openam_path, { class: 'btn btn-primary', target: '_blank' } do
    | AWS by OpenAM

.
  = link_to "#{ENV['ONELOGIN_URI']}", { class: 'btn btn-success', target: '_blank' } do
    | onelogin

.
  | onelogin Username: #{current_user.email unless current_user.nil?}
.
  | onelogin Password: #{current_user.encrypted_password unless current_user.nil?}

.
  = link_to aws_onelogin_path, { class: 'btn btn-success', target: '_blank' } do
    | AWS by onelogin

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | SsoBySamlSampleApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      header
        nav
          - if user_signed_in?
            strong
              = link_to current_user.email, root_path
            = link_to 'プロフィール変更', edit_user_registration_path
            = link_to 'ログアウト', destroy_user_session_path, method: :delete
          - else
            = link_to 'サインアップ', new_user_registration_path
            = link_to 'ログイン', new_user_session_path
      p.notice
        = notice
      p.alert
        = alert
      = yield